name: Generate Windows executable
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"  # Run only when a new version tag (e.g., v1.0.0) is pushed

jobs:
  gen-exe:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Generate executable
        run: |
          pyinstaller --onefile --name "EDH_matchmaker" --icon=media/icon.ico `
            --add-data "ui;ui" `
            --add-data "src;src" `
            --hidden-import=src.interface `
            --hidden-import=src.core `
            --hidden-import=src.misc `
            run_ui.py

      - name: Clean up build files
        run: |
          rm -r build
          rm EDH_matchmaker.spec
          mv dist/EDH_matchmaker.exe .

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: EDH_matchmaker
          path: EDH_matchmaker.exe
